#include "vk_glfw.h"

const char *vk_result_to_string(VkResult res)
{
	switch (res)
	{
		stringify_case(VK_SUCCESS);
		stringify_case(VK_NOT_READY);
		stringify_case(VK_TIMEOUT);
		stringify_case(VK_EVENT_SET);
		stringify_case(VK_EVENT_RESET);
		stringify_case(VK_INCOMPLETE);
		stringify_case(VK_ERROR_OUT_OF_HOST_MEMORY);
		stringify_case(VK_ERROR_OUT_OF_DEVICE_MEMORY);
		stringify_case(VK_ERROR_INITIALIZATION_FAILED);
		stringify_case(VK_ERROR_DEVICE_LOST);
		stringify_case(VK_ERROR_MEMORY_MAP_FAILED);
		stringify_case(VK_ERROR_LAYER_NOT_PRESENT);
		stringify_case(VK_ERROR_EXTENSION_NOT_PRESENT);
		stringify_case(VK_ERROR_FEATURE_NOT_PRESENT);
		stringify_case(VK_ERROR_INCOMPATIBLE_DRIVER);
		stringify_case(VK_ERROR_TOO_MANY_OBJECTS);
		stringify_case(VK_ERROR_FORMAT_NOT_SUPPORTED);
		stringify_case(VK_ERROR_FRAGMENTED_POOL);
		stringify_case(VK_ERROR_UNKNOWN);
		stringify_case(VK_ERROR_OUT_OF_POOL_MEMORY);
		stringify_case(VK_ERROR_INVALID_EXTERNAL_HANDLE);
		stringify_case(VK_ERROR_FRAGMENTATION);
		stringify_case(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS);
		stringify_case(VK_PIPELINE_COMPILE_REQUIRED);
		stringify_case(VK_ERROR_NOT_PERMITTED);
		stringify_case(VK_ERROR_SURFACE_LOST_KHR);
		stringify_case(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR);
		stringify_case(VK_SUBOPTIMAL_KHR);
		stringify_case(VK_ERROR_OUT_OF_DATE_KHR);
		stringify_case(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR);
		stringify_case(VK_ERROR_VALIDATION_FAILED_EXT);
		stringify_case(VK_ERROR_INVALID_SHADER_NV);
		stringify_case(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR);
		stringify_case(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR);
		stringify_case(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR);
		stringify_case(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR);
		stringify_case(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR);
		stringify_case(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR);
		stringify_case(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT);
		stringify_case(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT);
		stringify_case(VK_THREAD_IDLE_KHR);
		stringify_case(VK_THREAD_DONE_KHR);
		stringify_case(VK_OPERATION_DEFERRED_KHR);
		stringify_case(VK_OPERATION_NOT_DEFERRED_KHR);
		stringify_case(VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR);
		stringify_case(VK_ERROR_COMPRESSION_EXHAUSTED_EXT);
		stringify_case(VK_INCOMPATIBLE_SHADER_BINARY_EXT);
		stringify_case(VK_PIPELINE_BINARY_MISSING_KHR);
		stringify_case(VK_ERROR_NOT_ENOUGH_SPACE_KHR);
	default:
		return "UNKNOWN_VK_RESULT";
		break;
	}
}
